/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "outline": "#8c909f",
        "on-secondary": "#3c0091",
        "on-error": "#690005",
        "surface-background": "#0F172A",
        "on-secondary-fixed-variant": "#5516be",
        "surface-container-highest": "#32353c",
        "outline-variant": "#424754",
        "on-tertiary-fixed-variant": "#723600",
        "surface-border": "#334155",
        "error-container": "#93000a",
        "on-surface-variant": "#c2c6d6",
        "on-surface": "#e1e2ec",
        "primary-container": "#4d8eff",
        "on-tertiary": "#502400",
        "surface-container-high": "#272a31",
        "secondary-fixed": "#e9ddff",
        "on-error-container": "#ffdad6",
        "primary": "#adc6ff",
        "on-background": "#e1e2ec",
        "tertiary-fixed-dim": "#ffb786",
        "text-primary": "#F8FAFC",
        "inverse-primary": "#005ac2",
        "primary-fixed": "#d8e2ff",
        "surface-card": "#1E293B",
        "surface": "#10131a",
        "on-secondary-fixed": "#23005c",
        "on-tertiary-fixed": "#311400",
        "primary-fixed-dim": "#adc6ff",
        "inverse-surface": "#e1e2ec",
        "secondary-container": "#571bc1",
        "error": "#ffb4ab",
        "surface-tint": "#adc6ff",
        "on-primary-fixed-variant": "#004395",
        "surface-container": "#1d2027",
        "inverse-on-surface": "#2e3038",
        "surface-variant": "#32353c",
        "secondary-fixed-dim": "#d0bcff",
        "status-error": "#EF4444",
        "tertiary-fixed": "#ffdcc6",
        "surface-dim": "#10131a",
        "surface-container-lowest": "#0b0e15",
        "text-secondary": "#94A3B8",
        "status-success": "#10B981",
        "background": "#10131a",
        "surface-container-low": "#191b23",
        "on-secondary-container": "#c4abff",
        "secondary": "#d0bcff",
        "on-primary": "#002e6a",
        "surface-bright": "#363941",
        "on-tertiary-container": "#461f00",
        "tertiary": "#ffb786",
        "status-warning": "#F59E0B",
        "data-latency": "#A855F7",
        "on-primary-fixed": "#001a42",
        "on-primary-container": "#00285d",
        "tertiary-container": "#df7412"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "sidebar-width": "260px",
        "container-padding": "24px",
        "gutter": "16px",
        "stack-gap": "12px"
      },
      fontFamily: {
        "display-lg": ["Space Grotesk"],
        "mono-data": ["monospace"],
        "body-base": ["Inter"],
        "body-sm": ["Inter"],
        "label-caps": ["Inter"],
        "headline-md": ["Space Grotesk"]
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "mono-data": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-base": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}