sonar.projectKey=cerberus-api-monitoring-system
sonar.organization=my-org

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=Cerberus API Monitoring System
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=server/src

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Exclude tests from coverage
sonar.exclusions=server/src/tests/**, server/node_modules/**
sonar.javascript.lcov.reportPaths=server/coverage/lcov.info
